[phases.setup]
nixPkgs = ["python312", "gcc"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python manage.py migrate --noinput && python manage.py shell -c \"from scripts.create_admin import create_admin; create_admin()\" && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
