# Generated by Django 6.0.4 on 2026-04-21 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('dimension', models.CharField(choices=[('TYPE', '按类型'), ('SPACE', '按空间'), ('ORIGIN', '按产地')], max_length=10, verbose_name='维度')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '产品分类',
                'verbose_name_plural': '产品分类',
                'db_table': 'products_category',
                'ordering': ['sort_order', 'id'],
                'unique_together': {('parent', 'name', 'dimension')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='产品名称')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='产品编号')),
                ('description', models.TextField(blank=True, default='', verbose_name='产品描述')),
                ('origin', models.CharField(choices=[('IMPORT', '进口'), ('DOMESTIC', '国产'), ('CUSTOM', '定制')], default='DOMESTIC', max_length=10, verbose_name='产地')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='最低售价')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_products', to='products.category', verbose_name='主分类')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'db_table': 'products_product',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'products_product_category',
                'unique_together': {('product', 'category')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', through='products.ProductCategory', to='products.category', verbose_name='关联分类'),
        ),
        migrations.CreateModel(
            name='ProductConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(max_length=200, verbose_name='配置名称')),
                ('attributes', models.JSONField(blank=True, default=dict, verbose_name='自定义属性')),
                ('guide_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='指导价格')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='products.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '产品配置',
                'verbose_name_plural': '产品配置',
                'db_table': 'products_product_config',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=500, verbose_name='图片路径')),
                ('thumbnail_path', models.CharField(blank=True, default='', max_length=500, verbose_name='缩略图路径')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_cover', models.BooleanField(default=False, verbose_name='是否封面')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '产品图片',
                'verbose_name_plural': '产品图片',
                'db_table': 'products_product_image',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
