# Generated by Django 6.0.4 on 2026-04-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_update_dimensions_and_seed_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='dimension',
            field=models.CharField(choices=[('TYPE', '产品类别'), ('BRAND', '品牌')], max_length=10, verbose_name='维度'),
        ),
    ]
