# Generated by Django 6.0.4 on 2026-04-21 12:02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='报价单标题')),
                ('customer_name', models.CharField(blank=True, default='', max_length=200, verbose_name='客户名称')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('SENT', '已发送'), ('CONFIRMED', '已确认'), ('CANCELLED', '已取消')], default='DRAFT', max_length=15, verbose_name='状态')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('terms', models.TextField(blank=True, default='', verbose_name='条款')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='总金额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotes', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '报价单',
                'verbose_name_plural': '报价单',
                'db_table': 'quotes_quote',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='产品名称')),
                ('config_name', models.CharField(blank=True, default='', max_length=200, verbose_name='配置名称')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='折扣(%)')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='小计')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='关联产品')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotes.quote', verbose_name='报价单')),
            ],
            options={
                'verbose_name': '报价明细',
                'verbose_name_plural': '报价明细',
                'db_table': 'quotes_quote_item',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
