# Generated by Django 6.0.4 on 2026-04-21 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='分享令牌')),
                ('content_type', models.CharField(choices=[('PRODUCT', '产品'), ('CASE', '案例'), ('QUOTE', '报价单'), ('CATALOG', '产品图册')], max_length=10, verbose_name='内容类型')),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name='关联对象ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='分享标题')),
                ('password_hash', models.CharField(blank=True, default='', max_length=128, verbose_name='密码哈希')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('max_access_count', models.IntegerField(blank=True, null=True, verbose_name='最大访问次数')),
                ('access_count', models.IntegerField(default=0, verbose_name='已访问次数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shares', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '分享链接',
                'verbose_name_plural': '分享链接',
                'db_table': 'sharing_share_link',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShareAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True, verbose_name='访问时间')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='浏览器信息')),
                ('share_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='sharing.sharelink')),
            ],
            options={
                'verbose_name': '访问记录',
                'verbose_name_plural': '访问记录',
                'db_table': 'sharing_access_log',
                'ordering': ['-accessed_at'],
            },
        ),
    ]
