# Generated by Django 6.0.4 on 2026-04-21 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='案例标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='项目描述')),
                ('industry', models.CharField(choices=[('TECH', '科技/互联网'), ('FINANCE', '金融/保险/财税'), ('REALESTATE', '地产/建筑/设计院'), ('EDUCATION', '教育培训'), ('MEDICAL', '医疗/大健康'), ('MEDIA', '广告/文创/传媒'), ('MANUFACTURE', '制造/实业/工厂'), ('GOVERNMENT', '政府/国企/事业单位'), ('OTHER', '其他')], default='OTHER', max_length=20, verbose_name='行业分类')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cases', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '客户案例',
                'verbose_name_plural': '客户案例',
                'db_table': 'cases_case',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=500, verbose_name='图片路径')),
                ('thumbnail_path', models.CharField(blank=True, default='', max_length=500, verbose_name='缩略图路径')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_cover', models.BooleanField(default=False, verbose_name='是否封面')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cases.case', verbose_name='案例')),
            ],
            options={
                'verbose_name': '案例图片',
                'verbose_name_plural': '案例图片',
                'db_table': 'cases_case_image',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CaseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'cases_case_product',
                'unique_together': {('case', 'product')},
            },
        ),
        migrations.AddField(
            model_name='case',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='cases', through='cases.CaseProduct', to='products.product', verbose_name='关联产品'),
        ),
    ]
